---
title: "p8105_hw3_xc2473"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

options(digits = 3)
```

```{r}
library(tidyverse)
library(ggridges)

###Question 1

library(p8105.datasets)
data("instacart")

ins_df = 
  instacart %>%   
  janitor::clean_names()  

n_distinct(pull(ins_df, aisle))

aisle_df_10000 = 
  instacart %>% 
  group_by(aisle) %>%
     summarize(number_of_aisle = n()) %>% 
  filter(number_of_aisle > 10000) %>% 
  arrange(number_of_aisle)

###Make a plot that shows the number of items ordered in each aisle

aisle_df_10000 %>% 
  ggplot(aes(x = aisle, y = number_of_aisle)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = " Number of items ordered in each aisle (among aisles with more than 10000 items ordered) ")

###Make a table showing the three most popular items in each of the aisles

aisle_3popular_items = 
  ins_df %>% 
  filter(aisle == "baking ingredients" | aisle == "dog food care" | aisle == "packaged vegetables fruits") %>% 
  group_by(aisle, product_name) %>% 
  summarize(n = n()) %>% 
  mutate(rank = min_rank(desc(n))) %>% 
  filter(rank < 4) %>% 
  select(-n) %>% 
  pivot_wider(
    names_from = "rank",
    values_from = "product_name") %>% 
  select(aisle, most_popular = "1",  second_most_popular = "2", third_most_popular = "3") %>% 
  knitr::kable()

### Make a table showing the mean hour of the day at which Pink Lady Apples and Coffee Ice Cream are ordered on each day of the week
         
order_hour = 
  ins_df %>% 
  filter(product_name == "Pink Lady Apples" | product_name == "Coffee Ice Cream") %>% 
  select(product_name, order_dow, order_hour_of_day) %>% 
  group_by(product_name, order_dow) %>% 
  summarize(mean_hour = mean(order_hour_of_day)) %>% 
  pivot_wider(
    names_from = "product_name", 
    values_from = "mean_hour") %>% 
  select(-order_dow) %>% 
  knitr::kable(digits = 1)
    
#### Question 2
###
```


```{r}
library(p8105.datasets)
data("brfss_smart2010")

unique(pull(brfss_smart2010, Response))

brfss = 
  brfss_smart2010 %>% 
  janitor::clean_names() %>% 
  rename(state = locationabbr, county = locationdesc) %>% 
  filter(topic == "Overall Health") %>% 
  mutate(response = as.factor(response),
         response = fct_relevel(response, c("Poor", "Fair", "Good", "Very good", "Excellent"))) %>%
  arrange(response)
  
brfss_location =
  brfss %>% 
  filter(year == 2002 | year == 2010) %>% 
  group_by(year, state) %>% 
  summarize(county_number = n_distinct(county)) %>% 
  filter(county_number > 6)

unique(pull(brfss, response))

brfss_excellent = 
  brfss %>% 
  filter(response == "Excellent") %>% 
  group_by(year, state) %>% 
  summarize(average_value = mean(data_value, na.rm = TRUE)) 
  
brfss_excellent %>% 
  ggplot(aes(x = year, y = average_value, color = state)) + 
  geom_line(aes(group = state)) +
  labs(title = "Average value over time for each state")

brfss %>%
  filter(year == 2006 | year == 2010, state == "NY") %>% 
  ggplot(aes(x = response, y = data_value)) +
  geom_boxplot(aes(fill = response), color = "blue", alpha = .5) +
  facet_grid(~year)
  
### Question3
accl = read_csv(file = "./accel_data.csv") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    activity_1:activity_1440,
    names_to = "activity",
    names_prefix = "activity_",
    values_to = "value") 

a =
  accl %>% 
  filter(day == "Saturday", week == 4)

accl_day = 
  accl %>% 
  group_by(week, day) %>% 
  summarize(day_activity = sum(value, na.rm = TRUE)) %>% 
  mutate(weekdays_vs_weekends = ifelse(day == "Saturday", "Weekend",
                                       ifelse(day == "Sunday", "Weekend", "Weekday")))

accl_hour =
  accl %>%
  mutate(hour = ceiling(as.numeric(activity) / 60)) %>% 
  group_by(week, day, hour) %>% 
  summarize(hour_activity = sum(value, na.rm = TRUE)) %>% 
  group_by(day, hour) %>% 
  summarize(ave_activity = mean(hour_activity)) %>% 
  ungroup(day) %>% 
  mutate(day = as.factor(day),
         day = fct_relevel(day, c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))) 

accl_hour %>% 
ggplot(aes(x = hour, y = ave_activity, color = day)) + 
  geom_smooth(se = FALSE) +
  labs(title = "24-hour activity time courses for each day in a week")
 


```

